debounce: 300
ignore: \.git/
trig_async:
  - server
format:
  command_ok: "\u001b[38;5;240m[{{.Title}}] \u001b[0m{{.Message}}\n"
  command_err: "\u001b[38;5;240m[{{.Title}}] \u001b[38;5;1m{{.Message}}\u001b[0m\n"

rules:
  - name: server
    match: \.(go|yaml|html|js|css)$
    ignore: (_test\.go)
    command: go run app/cmd/main.go
    env:
      - type: file
        name: ./.env

  - name: test
    match: _test\.go$
    command: go test -cover {PKG}

  - name: lint
    match: \.go$
    ignore: (/mock/|_gen_?|(entity\.go)$)
    command: golangci-lint run {PKG}
    debounce: 1000
