version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: app-server
    ports:
      - 8083:8083
    volumes:
      - .:/app
    working_dir: /app
