FROM golang:1.17.1 AS build

WORKDIR /app

COPY app/ .
COPY go.mod ./

RUN go build -o main-server cmd/main.go

FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build app/main-server /main-server

EXPOSE 8083

USER nonroot:nonroot

ENTRYPOINT [ "/main-server" ]